### ISSUE TITLE
Criar documentação de como contribuir

### ISSUE THREAD

**Issue by vicmagpac** [LabCDBr/gestao#376]
### Tasks

- [ ] Atualizar o README para referenciar os templates abaixo
- [ ] Issues template (feature, bugs)
- [ ] Pull request template

### ReferÊncias

https://github.com/nodejs/nodejs.org

**Comment by vicmagpac** [comment]
Template de issues no repositório:

![image](https://github.com/LabCDBr/gestao/assets/3487411/99fff616-6c9a-4c33-9b67-dc56fca7447d)

**Comment by vicmagpac** [comment]
Template de pull request:

![image](https://github.com/LabCDBr/gestao/assets/3487411/f72662b1-ab71-4805-9570-ec3548601864)

**Comment by vicmagpac** [comment]
Realizamos uma proposta do readme.md para o rede mapas no seguinte link: https://github.com/RedeMapas/mapas/blob/feature/proposta-readme/README.md

Sugestão e melhorias são importantes !

**Comment by vicmagpac** [comment]
Oi @Narapessoa @uira @wforte88 @lpirola realizamos uma proposta do readme.md em um PR para validação.
Segue o link https://github.com/RedeMapas/mapas/blob/feature/proposta-readme/README.md
